// Code generated by internal/generate/api/main.go; DO NOT EDIT.

package caddy

import (
	"context"

	"github.com/browningluke/opnsense-go/pkg/api"
)

var HandleOpts = api.ReqOpts{
	AddEndpoint:         "/caddy/reverse_proxy/add_handle",
	GetEndpoint:         "/caddy/reverse_proxy/get_handle",
	UpdateEndpoint:      "/caddy/reverse_proxy/set_handle",
	DeleteEndpoint:      "/caddy/reverse_proxy/del_handle",
	ReconfigureEndpoint: caddyReconfigureEndpoint,
	Monad:               "handle",
}

// Data structs

type Handle struct {
	Enabled     string              `json:"enabled"`
	Reverse     api.SelectedMap     `json:"reverse"`
	Description string              `json:"description"`
	ToDomain    api.SelectedMapList `json:"ToDomain"`
	ToPort      string              `json:"ToPort"`
}

// CRUD operations

func (c *Controller) AddHandle(ctx context.Context, resource *Handle) (string, error) {
	return api.Add(c.Client(), ctx, HandleOpts, resource)
}

func (c *Controller) GetHandle(ctx context.Context, id string) (*Handle, error) {
	return api.Get(c.Client(), ctx, HandleOpts, &Handle{}, id)
}

func (c *Controller) UpdateHandle(ctx context.Context, id string, resource *Handle) error {
	return api.Update(c.Client(), ctx, HandleOpts, resource, id)
}

func (c *Controller) DeleteHandle(ctx context.Context, id string) error {
	return api.Delete(c.Client(), ctx, HandleOpts, id)
}
